require:
  - rubocop-performance # https://github.com/rubocop-hq/rubocop-performance/

AllCops:
  Exclude:
    - "vendor/**/*"
    - "bin/**/*"

Metrics/BlockLength:
  Exclude:
    - "./spec/**/*"
    - "toggl_integrator.gemspec"
